services:
  db:
    container_name: "db"
    image: "postgis/postgis:17-3.5"
    env_file: .env
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
