version: '3.9'

services:
  db:
    container_name: "db"
    image: "postgis/postgis:17-3.4"
    environment:
      - "POSTGRES_PASSWORD=123"
    expose:
      - "5432"
    ports:
      - "5555:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
